'use client';

import { useMemo, useState } from 'react';
import { motion, useReducedMotion } from 'framer-motion';
import { AlarmSmoke, BadgeCheck, CalendarClock, ChevronRight, Flame, Lightbulb, Mail, MapPin, Phone, ShieldCheck, Sparkles, ClipboardCheck, Menu, X } from 'lucide-react';

const LOGO = 'https://fueqkodtkzpkgyljuiui.supabase.co/storage/v1/object/public/business-logos/01c95810-24b8-42c9-b457-01d4bf4c4e28/logo-1783344661104.jpg';
const DS_LOGO = '/diamant-solutions-logo.svg';
const RECOMMENDATION_URL = 'https://www.woulduseagain.com/recommend/certifireukl-66c0e39f';

const PAYMENT_LINKS = {
  fra: 'https://book.stripe.com/7sYfZhanM37TahF2IQ1RC05',
  alarm: 'https://book.stripe.com/dRm4gzbrQ9wh3Th97e1RC06',
  emergency: 'https://book.stripe.com/8x27sL53s6k5gG31EM1RC02',
  weekly: 'https://buy.stripe.com/bJe28r7bAbEp4Xl1EM1RC03',
  monthly: 'https://buy.stripe.com/dRmeVd8fE0ZLfBZgzG1RC04',
};

const tickerItems = ['FIRE RISK ASSESSMENTS','ALARM SERVICING','EMERGENCY LIGHTING','FIRE SAFETY LOGGING'];

const services = [
  {icon:ClipboardCheck,title:'Fire Risk Assessment',price:'£195',copy:'A comprehensive assessment of your property, identifying potential fire hazards, reviewing existing safety measures and highlighting any improvements required. A full written Fire Risk Assessment report is provided following the inspection.',bookingUrl:PAYMENT_LINKS.fra,priceNote:'Includes up to 3 storeys. Each additional storey is £10, automatically calculated at checkout.'},
  {icon:AlarmSmoke,title:'Fire Alarm Certificate',price:'£95',copy:'Professional inspection and testing of your fire alarm system to check its operation and condition. A Fire Alarm Inspection & Servicing Certificate is issued, together with details of any faults or recommendations identified.',bookingUrl:PAYMENT_LINKS.alarm,priceNote:'Includes up to 3 storeys. Each additional storey is £10, automatically calculated at checkout.'},
  {icon:Lightbulb,title:'Emergency Lighting Certificate',price:'£75',copy:'Inspection and testing of your emergency lighting system to ensure the lights operate correctly in the event of a power failure. A certificate is provided with any faults or required remedial works clearly identified.',bookingUrl:PAYMENT_LINKS.emergency},
  {icon:CalendarClock,title:'Weekly / Monthly Fire Safety Logging',price:'£18 per visit',copy:'Regular on-site fire safety checks carried out weekly or monthly, depending on your requirements. Checks can include fire alarm testing, emergency lighting checks and other routine fire safety items, with each visit recorded in the property fire safety logbook.',logging:true}
];

const reveal={hidden:{opacity:0,y:28},visible:{opacity:1,y:0,transition:{duration:.62,ease:[.22,1,.36,1] as const}}};

export default function Home(){
 const reduceMotion=useReducedMotion();
 const [menuOpen,setMenuOpen]=useState(false);
 const [form,setForm]=useState({name:'',phone:'',email:'',service:'Fire Risk Assessment',message:''});
 const [status,setStatus]=useState<'idle'|'loading'|'success'|'error'>('idle');
 const embers=useMemo(()=>Array.from({length:18},(_,i)=>({left:`${(i*17+7)%100}%`,delay:`${(i%7)*.55}s`,duration:`${5+(i%5)}s`,size:`${2+(i%4)}px`})),[]);
 const footerEmbers=useMemo(()=>Array.from({length:5},(_,i)=>({left:`${12+i*19}%`,delay:`${i*1.15}s`,duration:`${7+i}s`,size:`${2+(i%2)}px`})),[]);
 const closeMenu=()=>setMenuOpen(false);
 async function submitForm(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setStatus('loading');try{const response=await fetch('/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});if(!response.ok)throw new Error('Request failed');setStatus('success');setForm({name:'',phone:'',email:'',service:'Fire Risk Assessment',message:''});}catch{setStatus('error');}}
 return <main>
 <header className="site-header"><a className="brand" href="#top" aria-label="Certifire UK home" onClick={closeMenu}><img src={LOGO} alt="Certifire UK"/><div><strong>Certifire UK</strong><span>Fire safety services</span></div></a><nav aria-label="Main navigation"><a href="#services">Services</a><a href="#process">How it works</a><a href="#about">About</a><a href="#contact">Contact</a></nav><a className="header-cta" href="#services">Book a service <ChevronRight size={17}/></a><button className="mobile-menu-toggle" type="button" aria-label={menuOpen?'Close menu':'Open menu'} aria-expanded={menuOpen} onClick={()=>setMenuOpen(v=>!v)}><span>Menu</span>{menuOpen?<X size={20}/>:<Menu size={20}/>}</button><div className={`mobile-menu${menuOpen?' open':''}`}><a href="#services" onClick={closeMenu}>Services <ChevronRight size={18}/></a><a href="#process" onClick={closeMenu}>How it works <ChevronRight size={18}/></a><a href="#about" onClick={closeMenu}>About <ChevronRight size={18}/></a><a href="#contact" onClick={closeMenu}>Contact <ChevronRight size={18}/></a><a className="mobile-book" href="#services" onClick={closeMenu}>Book online <ChevronRight size={18}/></a></div></header>
 <section className="hero" id="top"><div className="heat-orb heat-orb-one"/><div className="heat-orb heat-orb-two"/><div className="ember-field" aria-hidden="true">{embers.map((e,i)=><i key={i} style={{left:e.left,animationDelay:e.delay,animationDuration:e.duration,width:e.size,height:e.size}}/>)}</div><div className="hero-grid"/><div className="hero-content"><motion.div initial={reduceMotion?false:{opacity:0,y:16}} animate={{opacity:1,y:0}} transition={{duration:.55}} className="eyebrow"><Flame size={16}/> Fire safety support across London & surrounding areas</motion.div><motion.h1 initial={reduceMotion?false:{opacity:0,y:26}} animate={{opacity:1,y:0}} transition={{duration:.72,delay:.08}}>Fire safety that is<br/><span>clear, documented</span><br/>and kept on track.</motion.h1><motion.p initial={reduceMotion?false:{opacity:0,y:24}} animate={{opacity:1,y:0}} transition={{duration:.62,delay:.18}} className="hero-copy">Fire risk assessments, alarm servicing, emergency lighting checks and regular fire safety logging for properties across London and surrounding areas.</motion.p><motion.div initial={reduceMotion?false:{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{duration:.58,delay:.28}} className="hero-actions"><a className="btn btn-primary" href="#services">Book online <ChevronRight size={18}/></a><a className="btn btn-secondary" href="tel:+447308449574"><Phone size={17}/> 07308 449574</a></motion.div><div className="trust-row"><span><BadgeCheck size={18}/> BAFE registered</span><span><MapPin size={18}/> London & surrounding areas</span><span><CalendarClock size={18}/> Appointments within 7 working days</span></div></div><motion.aside initial={reduceMotion?false:{opacity:0,x:40,rotate:2}} animate={{opacity:1,x:0,rotate:0}} transition={{duration:.78,delay:.2}} className="hero-panel"><div className="panel-topline"><span>Certifire UK</span><span>Fire Safety</span></div><img className="hero-logo" src={LOGO} alt="Certifire UK logo"/><div className="panel-rule"/><p>Fire safety inspections, certification and ongoing logging for properties across London and surrounding areas.</p><div className="mini-list"><span><ShieldCheck size={18}/> Fire Risk Assessment</span><span><AlarmSmoke size={18}/> Fire Alarm Servicing</span><span><Lightbulb size={18}/> Emergency Lighting</span><span><ClipboardCheck size={18}/> Weekly / Monthly Logging</span></div><div className="panel-flare"/></motion.aside></section>
 <section className="ticker" aria-label="Certifire services"><div className="ticker-track">{[0,1,2,3].map(group=><div className="ticker-group" key={group} aria-hidden={group>0}>{tickerItems.map(item=><span className="ticker-item" key={`${group}-${item}`}><b>{item}</b><i>•</i></span>)}</div>)}</div></section>
 <section className="section services-section" id="services"><motion.div variants={reveal} initial="hidden" whileInView="visible" viewport={{once:true,amount:.2}} className="section-heading"><div><span className="section-kicker">Services & pricing</span><h2>Choose the service you need.</h2></div><p>Clear, upfront pricing with online booking available for every service.</p></motion.div><div className="services-grid">{services.map((service,index)=>{const Icon=service.icon;return <motion.article key={service.title} initial={reduceMotion?false:{opacity:0,y:34}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.18}} transition={{duration:.55,delay:index*.07}} className="service-card"><div className="service-number">0{index+1}</div><div className="service-icon"><Icon/></div><h3>{service.title}</h3><div className="price">{service.price}</div>{service.priceNote&&<div className="price-note">{service.priceNote}</div>}<p>{service.copy}</p>{service.logging?<div className="logging-actions"><a className="service-action" href={PAYMENT_LINKS.weekly}>Book weekly <ChevronRight size={17}/></a><a className="service-action secondary-action" href={PAYMENT_LINKS.monthly}>Book monthly <ChevronRight size={17}/></a></div>:<a className="service-action" href={service.bookingUrl}>Book & pay securely <ChevronRight size={17}/></a>}</motion.article>})}</div></section>
 <section className="process-wrap" id="process"><div className="process-glow"/><div className="section process-inner"><motion.div variants={reveal} initial="hidden" whileInView="visible" viewport={{once:true}} className="process-copy"><span className="section-kicker">How online booking works</span><h2>Book online. We’ll take care of the rest.</h2><p>Once booked, Certifire will arrange attendance within the next 7 working days.</p><a className="btn btn-primary" href="#services">Choose a service <ChevronRight size={18}/></a></motion.div><div className="steps">{[['01','Choose your service','Choose the inspection, certificate or logging service you need.'],['02','Tell us about the property','Add the property details and let us know how we can gain access.'],['03','Confirm your booking','Complete your details and payment online.'],['04','We arrange your visit','Certifire will arrange attendance within the next 7 working days.']].map(([n,title,copy])=><motion.div key={n} initial={reduceMotion?false:{opacity:0,x:20}} whileInView={{opacity:1,x:0}} viewport={{once:true}} className="step"><strong>{n}</strong><div><h3>{title}</h3><p>{copy}</p></div></motion.div>)}</div></div></section>
 <section className="section about-section" id="about"><motion.div initial={reduceMotion?false:{opacity:0,scale:.96}} whileInView={{opacity:1,scale:1}} viewport={{once:true}} className="about-card"><div className="about-mark"><Flame/></div><div><span className="section-kicker">About Certifire UK</span><h2>Fire safety services across London.</h2><p>Certifire UK provides fire risk assessments, fire alarm servicing, emergency lighting checks and regular fire safety logging for properties across London and surrounding areas.</p></div><div className="about-stats"><div><strong>4</strong><span>core services</span></div><div><strong>7</strong><span>working days for attendance</span></div><div><strong>£18</strong><span>per logging visit</span></div></div></motion.div></section>
 <section className="recommendation-section"><motion.div initial={reduceMotion?false:{opacity:0,y:24}} whileInView={{opacity:1,y:0}} viewport={{once:true}} className="recommendation-card"><div className="recommendation-icon"><BadgeCheck/></div><div className="recommendation-copy"><span className="section-kicker">Used Certifire UK?</span><h2>We’d love to hear from you.</h2><p>If you were happy with our service, leave us a recommendation and help others choose Certifire with confidence.</p></div><a className="btn btn-primary recommendation-button" href={RECOMMENDATION_URL} target="_blank" rel="noopener noreferrer">Leave us a recommendation <ChevronRight size={18}/></a></motion.div></section>
 <section className="contact-section" id="contact"><div className="lower-ember-field" aria-hidden="true">{footerEmbers.map((e,i)=><i key={i} style={{left:e.left,animationDelay:e.delay,animationDuration:e.duration,width:e.size,height:e.size}}/>)}</div><div className="section contact-grid"><motion.div variants={reveal} initial="hidden" whileInView="visible" viewport={{once:true}} className="contact-copy"><span className="section-kicker">General enquiries</span><h2>Have a question or need something different?</h2><p>Send us a message and we’ll get back to you.</p><div className="contact-links"><a href="tel:+447308449574"><Phone/><span><small>Call / WhatsApp</small>07308 449574</span></a><a href="mailto:certifireukltd@gmail.com"><Mail/><span><small>Email</small>certifireukltd@gmail.com</span></a><div><MapPin/><span><small>Area covered</small>London & surrounding areas</span></div></div></motion.div><motion.form initial={reduceMotion?false:{opacity:0,y:28}} whileInView={{opacity:1,y:0}} viewport={{once:true}} className="contact-form" onSubmit={submitForm}><div className="form-row"><label>Name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Your name"/></label><label>Phone<input required value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} placeholder="Your number"/></label></div><label>Email<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="Your email"/></label><label>Service<select value={form.service} onChange={e=>setForm({...form,service:e.target.value})}>{services.map(service=><option key={service.title}>{service.title}</option>)}<option>Other / General enquiry</option></select></label><label>Property / enquiry details<textarea rows={5} value={form.message} onChange={e=>setForm({...form,message:e.target.value})} placeholder="Tell us what you need"/></label><button className="btn btn-primary form-submit" type="submit" disabled={status==='loading'}>{status==='loading'?'Sending…':<>Send enquiry <ChevronRight size={18}/></>}</button><div className="form-status" aria-live="polite">{status==='success'&&<span className="success"><Sparkles size={16}/> Thank you. Your enquiry has been sent.</span>}{status==='error'&&<span className="error">Something went wrong. Please call or WhatsApp 07308 449574.</span>}</div></motion.form></div></section>
 <footer><div className="footer-main"><a className="brand footer-brand" href="#top"><img src={LOGO} alt="Certifire UK"/><div><strong>Certifire UK</strong><span>Fire safety services</span></div></a><p>Fire risk assessments, fire alarm servicing, emergency lighting checks and regular fire safety logging across London and surrounding areas.</p><div className="footer-links"><a href="#services">Services</a><a href="#process">How it works</a><a href="#contact">Contact</a></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Certifire UK Ltd. All rights reserved.</span><a className="diamant-credit" href="https://diamantsolutions.co.uk" target="_blank" rel="noopener noreferrer"><div className="credit-brand-row"><span>Built by</span><img src={DS_LOGO} alt="Diamant Solutions"/></div><span className="credit-tagline">Websites • Systems • Automation</span></a></div></footer>
 </main>;
}
